apiVersion: v1
kind: ReplicationController 
metadata:
  name: mynignx0-rc
spec:
  replicas: 4
  selectors: 
     app: mynginx 
  tempalte: 
   metadata: 
      labels: 
         app: mynginx 
  spec: 
    containers:
    - name: first-container
      image: ngiex 
      ports:
       - containserPort: 80